export interface Player {
  name: string;
  position: "GK" | "DEF" | "MID" | "FWD";
  rating: number;
}

export interface TeamSeason {
  club: string;
  season: string;
  players: Player[];
}

export const teamSeasons: TeamSeason[] = [
  {
    club: "Ajax",
    season: "2018/19",
    players: [
      { name: "André Onana", position: "GK", rating: 84 },
      { name: "Kostas Lamprou", position: "GK", rating: 70 },
      { name: "Matthijs de Ligt", position: "DEF", rating: 88 },
      { name: "Daley Blind", position: "DEF", rating: 84 },
      { name: "Nicolás Tagliafico", position: "DEF", rating: 83 },
      { name: "Noussair Mazraoui", position: "DEF", rating: 78 },
      { name: "Joël Veltman", position: "DEF", rating: 78 },
      { name: "Frenkie de Jong", position: "MID", rating: 88 },
      { name: "Lasse Schöne", position: "MID", rating: 81 },
      { name: "Donny van de Beek", position: "MID", rating: 83 },
      { name: "Hakim Ziyech", position: "MID", rating: 85 },
      { name: "Dušan Tadić", position: "FWD", rating: 86 },
      { name: "David Neres", position: "FWD", rating: 82 },
      { name: "Kasper Dolberg", position: "FWD", rating: 78 },
      { name: "Klaas-Jan Huntelaar", position: "FWD", rating: 78 },
    ],
  },
  {
    club: "PSV",
    season: "2014/15",
    players: [
      { name: "Jeroen Zoet", position: "GK", rating: 82 },
      { name: "Remko Pasveer", position: "GK", rating: 72 },
      { name: "Jeffrey Bruma", position: "DEF", rating: 79 },
      { name: "Karim Rekik", position: "DEF", rating: 76 },
      { name: "Santiago Arias", position: "DEF", rating: 79 },
      { name: "Jetro Willems", position: "DEF", rating: 77 },
      { name: "Héctor Moreno", position: "DEF", rating: 80 },
      { name: "Andrés Guardado", position: "MID", rating: 82 },
      { name: "Georginio Wijnaldum", position: "MID", rating: 84 },
      { name: "Davy Pröpper", position: "MID", rating: 80 },
      { name: "Adam Maher", position: "MID", rating: 76 },
      { name: "Memphis Depay", position: "FWD", rating: 85 },
      { name: "Luuk de Jong", position: "FWD", rating: 80 },
      { name: "Florian Jozefzoon", position: "FWD", rating: 73 },
      { name: "Jürgen Locadia", position: "FWD", rating: 75 },
    ],
  },
  {
    club: "Feyenoord",
    season: "2016/17",
    players: [
      { name: "Brad Jones", position: "GK", rating: 78 },
      { name: "Kenneth Vermeer", position: "GK", rating: 75 },
      { name: "Eric Botteghin", position: "DEF", rating: 77 },
      { name: "Terence Kongolo", position: "DEF", rating: 77 },
      { name: "Rick Karsdorp", position: "DEF", rating: 78 },
      { name: "Miquel Nelom", position: "DEF", rating: 73 },
      { name: "Jan-Arie van der Heijden", position: "DEF", rating: 75 },
      { name: "Karim El Ahmadi", position: "MID", rating: 78 },
      { name: "Tonny Vilhena", position: "MID", rating: 77 },
      { name: "Jens Toornstra", position: "MID", rating: 78 },
      { name: "Steven Berghuis", position: "MID", rating: 80 },
      { name: "Dirk Kuyt", position: "FWD", rating: 79 },
      { name: "Nicolai Jørgensen", position: "FWD", rating: 80 },
      { name: "Eljero Elia", position: "FWD", rating: 76 },
      { name: "Michiel Kramer", position: "FWD", rating: 73 },
    ],
  },
  {
    club: "AZ",
    season: "2008/09",
    players: [
      { name: "Sergio Romero", position: "GK", rating: 80 },
      { name: "Joey Didulica", position: "GK", rating: 72 },
      { name: "Niklas Moisander", position: "DEF", rating: 78 },
      { name: "Kew Jaliens", position: "DEF", rating: 76 },
      { name: "Héctor Moreno", position: "DEF", rating: 77 },
      { name: "Gill Swerts", position: "DEF", rating: 74 },
      { name: "Sébastien Pocognoli", position: "DEF", rating: 75 },
      { name: "Stijn Schaars", position: "MID", rating: 79 },
      { name: "Demy de Zeeuw", position: "MID", rating: 79 },
      { name: "David Mendes da Silva", position: "MID", rating: 77 },
      { name: "Maarten Martens", position: "MID", rating: 77 },
      { name: "Mounir El Hamdaoui", position: "FWD", rating: 82 },
      { name: "Moussa Dembélé", position: "FWD", rating: 81 },
      { name: "Ari", position: "FWD", rating: 76 },
      { name: "Graziano Pellè", position: "FWD", rating: 75 },
    ],
  },
  {
    club: "Ajax",
    season: "2010/11",
    players: [
      { name: "Maarten Stekelenburg", position: "GK", rating: 83 },
      { name: "Kenneth Vermeer", position: "GK", rating: 73 },
      { name: "Jan Vertonghen", position: "DEF", rating: 84 },
      { name: "Toby Alderweireld", position: "DEF", rating: 82 },
      { name: "Gregory van der Wiel", position: "DEF", rating: 81 },
      { name: "Vurnon Anita", position: "DEF", rating: 77 },
      { name: "Daley Blind", position: "DEF", rating: 75 },
      { name: "Christian Eriksen", position: "MID", rating: 80 },
      { name: "Eyong Enoh", position: "MID", rating: 76 },
      { name: "Demy de Zeeuw", position: "MID", rating: 78 },
      { name: "Siem de Jong", position: "MID", rating: 78 },
      { name: "Luis Suárez", position: "FWD", rating: 86 },
      { name: "Mounir El Hamdaoui", position: "FWD", rating: 80 },
      { name: "Dmitri Bulykin", position: "FWD", rating: 75 },
      { name: "Miralem Sulejmani", position: "FWD", rating: 76 },
    ],
  },
  {
    club: "PSV",
    season: "2017/18",
    players: [
      { name: "Jeroen Zoet", position: "GK", rating: 82 },
      { name: "Hidde Jurjus", position: "GK", rating: 70 },
      { name: "Nicolas Isimat-Mirin", position: "DEF", rating: 77 },
      { name: "Daniel Schwaab", position: "DEF", rating: 78 },
      { name: "Santiago Arias", position: "DEF", rating: 80 },
      { name: "Joshua Brenet", position: "DEF", rating: 76 },
      { name: "Derrick Luckassen", position: "DEF", rating: 75 },
      { name: "Marco van Ginkel", position: "MID", rating: 79 },
      { name: "Jorrit Hendrix", position: "MID", rating: 76 },
      { name: "Bart Ramselaar", position: "MID", rating: 74 },
      { name: "Gastón Pereiro", position: "MID", rating: 77 },
      { name: "Hirving Lozano", position: "FWD", rating: 82 },
      { name: "Steven Bergwijn", position: "FWD", rating: 79 },
      { name: "Luuk de Jong", position: "FWD", rating: 80 },
      { name: "Jürgen Locadia", position: "FWD", rating: 76 },
    ],
  },
];
